apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageiq
  labels:
    app: manageiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manageiq
  template:
    metadata:
      labels:
        app: manageiq
    spec:
      containers:
      - name: manageiq
        image: bmst/manageiq
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: manageiq
  labels:
    app: manageiq
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: manageiq
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: manageiq
spec:
  rules:
  - host: manageiq
    http:
      paths:
      - backend:
          serviceName: manageiq
          servicePort: http
        path: /
